# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gootube
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: gootube
# "service" is the name of this project. This will also be added to your AWS resource names.
service: notion-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  rateHandler:
    handler: index.handler
    events:
      - schedule:
          rate: cron(0 17 * * ? *)  #Trigger every day at 17:00 UTC - 00:00 GMT+7
          description: Trigger review today attempt
      - schedule:
          rate: cron(0 1 * * ? *)   #Trigger every day at 01:00 UTC - 08:00 GMT+7
          description: Trigger generate today attempt
