# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: gootube
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: gootube
# "service" is the name of this project. This will also be added to your AWS resource names.
service: notion-service

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  environment:
    NOTION_API_KEY: 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
    NOTION_WORD_LIST_DATABASE_ID: 150c3752e48a803e8593c48e9593332e
    NOTION_ATTEMPTS_DATABASE_ID: 150c3752e48a80768126d6eac82027f7
    NOTION_PRACTICE_LIST_DATABASE_ID: 169c3752e48a80e79603f720fe19a222
    NOTION_ROUTINE_LIST_DATABASE_ID: 168c3752e48a80a8b7a6d6f3d231aa45
    NOTION_RECORD_LIST_DATABASE_ID: 169c3752e48a80ed86abe75ccb61f7e6
    NOTION_REPORTS_DATABASE_ID: 169c3752e48a8046b5e4c44669362023
    TELEGRAM_URL: https://api.telegram.org/bot7014099402:AAG15B_W2pW6k2gFRWZ_BJHSSdgJMpsSfRg/sendMessage?chat_id=-1002322494245&text={{message}}&message_thread_id=6
    NODE_ENV: production

package:
  patterns:
    - '!.env'
    - '!README.md'

functions:
  generateHandler:
    handler: generateHandler.handler
    events:
      - schedule:
          rate: cron(0 1 * * ? *)   #Trigger every day at 01:00 UTC - 08:00 GMT+7
          description: Trigger generate today attempt
    timeout: 900

  routineHandler:
    handler: routineHandler.handler
    events:
      - schedule:
          rate: cron(0 23 * * ? *)   #Trigger every day at 23:00 UTC - 06:00 GMT+7
          description: Trigger generate today checklist
    timeout: 900
    
  urlHandler:
    handler: urlHandler.handler
    url:
      authorizer: aws_iam
    timeout: 60
